version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "dalberto"
    commit-message:
      prefix: "ci"
      include: "scope"